# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

# React Native configuration
require_relative '../MyRNFramework/node_modules/react-native/scripts/react_native_pods'
require_relative '../MyRNFramework/node_modules/@react-native-community/cli-platform-ios/native_modules'

# Flipper configuration (disable for release builds)
flipper_config = ENV['NO_FLIPPER'] == '1' ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

target 'RNBridgeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  
  # Use React Native
  config = use_native_modules!
  
  use_react_native!(
    :path => '../MyRNFramework/node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => flipper_config,
    # An absolute path to your application root
    :app_path => "#{Pod::Config.instance.installation_root}/../MyRNFramework"
  )

  # React Native Brownfield library for brownfield integration
  pod 'react-native-brownfield', :path => '../MyRNFramework/node_modules/@callstack/react-native-brownfield'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      '../MyRNFramework/node_modules/react-native',
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end
  end
end
